import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lets run cypress</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Know Me!
        </h1> 
        <h1 >Who are you ?</h1>
        <br />
        <div className={styles.grid}>
          <label>What is your Hobbie : </label>
          <input className={styles.code} type="text" data-cy="hobby"></input>
        </div>
        <br />
        <br />
        <div className={styles.grid}>
          <Link href="decision">
            <button data-cy="matchButton"> What is my Hobbies</button>
          </Link>
        </div>
      </main>
    </div>
  )
}
