import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import {useRef,useState} from "react";
import { useRouter } from 'next/router'

export default function Home() {
	const router = useRouter()
	const hobbieRef = useRef("");
	
	const onClickHandler = (e)=>{
		const hobbies = hobbieRef.current.value;
		router.push(`/${hobbies}`)
    e.preventDefault();
	}
  return (
    <div className={styles.container} >
      <Head>
        <title>Lets run cypress</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Know Me!
        </h1> 
        <h1 >Who are you ?</h1>
        <br />
        <div className={styles.grid}>
          <label>What is your Hobbie : </label>
          <input className={styles.style3} type="text" data-cy="hobby" ref={hobbieRef}></input>
        </div>
        <br />
        <br />
        <div className={styles.grid}>
         
            <button data-cy="matchButton" className={styles.button} onClick={onClickHandler}> What is my Hobbies</button>
         
        </div>
      </main>
    </div>
		
  )
}
